name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Notify to Typetalk
        uses: shomatan/typetalk-action@master
        env:
          TYPETALK_TOKEN: ${{ secrets.TYPETALK_TOKEN }}
        with:
          topic-id: 66879
          message: "Action success :smile:"
